// src/typescript/packages/forms-modeler-react/src/index.tsx
import { useEffect, useId, useMemo, useRef, useState, type ReactNode } from "react";
import { mountJsonEditor, type JsonEditorDiagnostic, type JsonEditorHandle } from "@orbyss/program-kit-forms-codemirror";
import {
  FormModelerSession,
  parseFormModelerDocument,
  projectFormModelerGraph,
  serializeFormModelerDocument,
  type FormModelerAction,
  type FormModelerActionCatalog,
  type FormModelerComponentCatalog,
  type FormModelerDocument,
  type FormModelerElement,
  type FormModelerField,
  type FormModelerOperation,
  type FormModelerSnapshot
} from "@orbyss/program-kit-forms-modeler";

export type FormModelerView = "design" | "json" | "graph";
export type FormModelerEditorMode = "codemirror" | "strictCsp";
export type FormModelerPaletteItem =
  | { readonly id: string; readonly label: string; readonly category: string; readonly type: "field"; readonly valueKind: FormModelerField["valueKind"] }
  | { readonly id: string; readonly label: string; readonly category: string; readonly type: "element"; readonly elementKind: "group" | "horizontalLayout" | "verticalLayout" | "text" };

export const defaultFormModelerPalette: readonly FormModelerPaletteItem[] = Object.freeze([
  { id: "text-field", label: "Add text field", category: "Fields", type: "field", valueKind: "string" },
  { id: "number-field", label: "Add number field", category: "Fields", type: "field", valueKind: "number" },
  { id: "boolean-field", label: "Add yes/no field", category: "Fields", type: "field", valueKind: "boolean" },
  { id: "group", label: "Add group", category: "Layout", type: "element", elementKind: "group" },
  { id: "horizontal-layout", label: "Add horizontal layout", category: "Layout", type: "element", elementKind: "horizontalLayout" },
  { id: "vertical-layout", label: "Add vertical layout", category: "Layout", type: "element", elementKind: "verticalLayout" },
  { id: "text", label: "Add explanatory text", category: "Content", type: "element", elementKind: "text" }
]);

export interface ProgramKitFormModelerLabels {
  readonly undo: string;
  readonly redo: string;
  readonly commit: string;
  readonly applyJson: string;
  readonly design: string;
  readonly json: string;
  readonly graph: string;
  readonly structure: string;
  readonly inspector: string;
  readonly editor: string;
  readonly nodes: string;
  readonly relationships: string;
  readonly diagnostics: string;
  readonly palette: string;
  readonly canvas: string;
  readonly preview: string;
}

export interface ProgramKitFormModelerProps {
  readonly session: FormModelerSession;
  readonly initialView?: FormModelerView;
  readonly labels?: Partial<ProgramKitFormModelerLabels>;
  readonly actionCatalog?: FormModelerActionCatalog;
  readonly componentCatalog?: FormModelerComponentCatalog;
  readonly paletteItems?: readonly FormModelerPaletteItem[];
  /** Trusted application renderer; preview code never comes from the form document. */
  readonly renderPreview?: (document: FormModelerDocument) => ReactNode;
  /** CodeMirror is the default. Use strictCsp when style attributes are prohibited by policy. */
  readonly editorMode?: FormModelerEditorMode;
  /** Nonce for CodeMirror's generated stylesheet; it does not authorize runtime style attributes. */
  readonly cspNonce?: string;
  readonly onChange?: (snapshot: FormModelerSnapshot) => void;
  readonly onCommit?: (document: FormModelerDocument, sequence: number) => void | Promise<void>;
}

const defaults: ProgramKitFormModelerLabels = Object.freeze({
  undo: "Undo", redo: "Redo", commit: "Commit changes", applyJson: "Apply JSON",
  design: "Design", json: "JSON", graph: "Graph", structure: "Form structure",
  inspector: "Properties", editor: "Form JSON", nodes: "Form nodes", relationships: "Relationships",
  diagnostics: "Modeler diagnostics", palette: "Component palette", canvas: "Layout canvas", preview: "Live preview"
});

export function ProgramKitFormModeler({ session, initialView = "design", labels: overrides, actionCatalog, componentCatalog, paletteItems = defaultFormModelerPalette, renderPreview, editorMode = "codemirror", cspNonce, onChange, onCommit }: ProgramKitFormModelerProps): ReactNode {
  const instanceId = useId();
  const labels = { ...defaults, ...overrides };
  const [view, setView] = useState<FormModelerView>(initialView);
  const [snapshot, setSnapshot] = useState(() => session.snapshot());
  const [source, setSource] = useState(() => serializeFormModelerDocument(snapshot.document));
  const [sourceError, setSourceError] = useState("");
  const bindingDiagnostics = [
    ...(actionCatalog?.validateBindings(snapshot.document.actions) ?? []),
    ...(componentCatalog?.validateBindings(snapshot.document.fields) ?? [])
  ];
  const commandSequence = useRef(0);
  const refresh = (next: FormModelerSnapshot) => {
    setSnapshot(next);
    setSource(serializeFormModelerDocument(next.document));
    setSourceError("");
    onChange?.(next);
  };
  const apply = (operations: readonly FormModelerOperation[]) => refresh(session.apply({
    commandId: `modeler-${snapshot.sequence}-${++commandSequence.current}`,
    expectedSequence: snapshot.sequence,
    operations
  }));
  const addPaletteItem = (item: FormModelerPaletteItem) => {
    const addition = createPaletteAddition(snapshot.document, snapshot.selectedId, item);
    apply(addition.operations);
    refreshSelection(session.select(addition.selectedId), setSnapshot, onChange);
  };
  const select = (id: string) => refreshSelection(session.select(id), setSnapshot, onChange);
  const applySource = () => {
    try {
      const document = parseFormModelerDocument(source);
      apply([{ type: "replaceDocument", document }]);
    } catch (error) {
      setSourceError(error instanceof Error ? error.message : "The JSON document is invalid.");
    }
  };

  return (
    <section className="pk-form-modeler" data-view={view}>
      <div aria-label="Modeler actions" className="pk-form-modeler__toolbar" role="toolbar">
        <button disabled={!snapshot.canUndo} onClick={() => refresh(session.undo())} type="button">{labels.undo}</button>
        <button disabled={!snapshot.canRedo} onClick={() => refresh(session.redo())} type="button">{labels.redo}</button>
        {onCommit !== undefined && <button disabled={bindingDiagnostics.length > 0} onClick={() => { void onCommit(snapshot.document, snapshot.sequence); }} type="button">{labels.commit}</button>}
      </div>
      {bindingDiagnostics.length > 0 && <div aria-label={labels.diagnostics} className="pk-form-modeler__diagnostics" role="alert"><ul>{bindingDiagnostics.map(diagnostic => <li key={`${diagnostic.code}-${diagnostic.path}`}>{diagnostic.message}</li>)}</ul></div>}
      <div aria-label="Modeler views" className="pk-form-modeler__tabs" role="tablist">
        {(["design", "json", "graph"] as const).map(candidate => (
          <button aria-controls={`${instanceId}-${candidate}-panel`} aria-selected={view === candidate} id={`${instanceId}-${candidate}-tab`} key={candidate} onClick={() => setView(candidate)} role="tab" type="button">
            {labels[candidate]}
          </button>
        ))}
      </div>
      {view === "design" && (
        <div aria-labelledby={`${instanceId}-design-tab`} className="pk-form-modeler__workspace" id={`${instanceId}-design-panel`} role="tabpanel">
          <FormModelerPalette items={paletteItems} label={labels.palette} onAdd={addPaletteItem} />
          <div className="pk-form-modeler__design">
            <FormModelerTree document={snapshot.document} label={labels.structure} onSelect={select} selectedId={snapshot.selectedId} />
            <FormModelerCanvas document={snapshot.document} label={labels.canvas} onSelect={select} selectedId={snapshot.selectedId} />
            <section aria-label={labels.preview} className="pk-form-modeler__preview"><h2>{labels.preview}</h2>{renderPreview?.(snapshot.document) ?? <p>{snapshot.document.fields.length} fields · {countElements(snapshot.document.layout)} layout blocks</p>}</section>
          </div>
          <FormModelerInspector actionCatalog={actionCatalog} componentCatalog={componentCatalog} document={snapshot.document} label={labels.inspector} onApply={apply} selectedId={snapshot.selectedId} />
        </div>
      )}
      {view === "json" && (
        <div aria-labelledby={`${instanceId}-json-tab`} className="pk-form-modeler__panel" id={`${instanceId}-json-panel`} role="tabpanel">
          <FormModelerJsonEditor accessibleLabel={labels.editor} {...(cspNonce === undefined ? {} : { cspNonce })} mode={editorMode} onChange={setSource} source={source} />
          <button onClick={applySource} type="button">{labels.applyJson}</button>
          {sourceError.length > 0 && <pre className="pk-form-modeler__error" role="alert">{sourceError}</pre>}
        </div>
      )}
      {view === "graph" && <FormModelerGraph document={snapshot.document} labelledBy={`${instanceId}-graph-tab`} labels={labels} onSelect={select} panelId={`${instanceId}-graph-panel`} selectedId={snapshot.selectedId} />}
    </section>
  );
}

export function FormModelerPalette({ items, label, onAdd }: { readonly items: readonly FormModelerPaletteItem[]; readonly label: string; readonly onAdd: (item: FormModelerPaletteItem) => void }): ReactNode {
  const categories = [...new Set(items.map(item => item.category))];
  return <aside aria-label={label} className="pk-form-modeler__palette"><h2>{label}</h2>{categories.map(category => <section key={category}><h3>{category}</h3><div>{items.filter(item => item.category === category).map(item => <button key={item.id} onClick={() => onAdd(item)} type="button">{item.label}</button>)}</div></section>)}</aside>;
}

export function FormModelerCanvas({ document, label, selectedId, onSelect }: { readonly document: FormModelerDocument; readonly label: string; readonly selectedId: string | undefined; readonly onSelect: (id: string) => void }): ReactNode {
  const fields = new Map(document.fields.map(field => [field.id, field]));
  return <section aria-label={label} className="pk-form-modeler__canvas"><h2>{label}</h2><CanvasElement element={document.layout} fields={fields} onSelect={onSelect} selectedId={selectedId} /></section>;
}

function CanvasElement({ element, fields, selectedId, onSelect }: { readonly element: FormModelerElement; readonly fields: ReadonlyMap<string, FormModelerField>; readonly selectedId: string | undefined; readonly onSelect: (id: string) => void }): ReactNode {
  const field = element.fieldId === undefined || element.fieldId === null ? undefined : fields.get(element.fieldId);
  return <div className="pk-form-modeler__canvas-block" data-kind={element.kind}><button aria-pressed={selectedId === element.id} onClick={() => onSelect(element.id)} type="button"><strong>{field?.label.defaultText ?? element.text?.defaultText ?? element.id}</strong><small>{element.kind}</small></button>{element.elements.length > 0 && <div className="pk-form-modeler__canvas-children">{element.elements.map(child => <CanvasElement element={child} fields={fields} key={child.id} onSelect={onSelect} selectedId={selectedId} />)}</div>}</div>;
}

export interface FormModelerTreeProps { readonly document: FormModelerDocument; readonly label: string; readonly selectedId: string | undefined; readonly onSelect: (id: string) => void; }
export function FormModelerTree({ document, label, selectedId, onSelect }: FormModelerTreeProps): ReactNode {
  return <nav aria-label={label} className="pk-form-modeler__tree"><ul>
    <TreeButton id={document.id} label={document.name} selectedId={selectedId} onSelect={onSelect} />
    <li><span>Fields</span><ul>{document.fields.map(field => <TreeButton id={field.id} key={field.id} label={field.label.defaultText} selectedId={selectedId} onSelect={onSelect} />)}</ul></li>
    <li><span>Layout</span><ElementTree element={document.layout} selectedId={selectedId} onSelect={onSelect} /></li>
    <li><span>Actions</span><ul>{document.actions.map(action => <TreeButton id={action.id} key={action.id} label={action.label.defaultText} selectedId={selectedId} onSelect={onSelect} />)}</ul></li>
  </ul></nav>;
}

function ElementTree({ element, selectedId, onSelect }: { readonly element: FormModelerElement; readonly selectedId: string | undefined; readonly onSelect: (id: string) => void }): ReactNode {
  return <ul><TreeButton id={element.id} label={`${element.id} · ${element.kind}`} selectedId={selectedId} onSelect={onSelect} />{element.elements.map(child => <li key={child.id}><ElementTree element={child} selectedId={selectedId} onSelect={onSelect} /></li>)}</ul>;
}
function TreeButton({ id, label, selectedId, onSelect }: { readonly id: string; readonly label: string; readonly selectedId: string | undefined; readonly onSelect: (id: string) => void }): ReactNode {
  return <li><button aria-current={selectedId === id} onClick={() => onSelect(id)} type="button">{label}</button></li>;
}

interface InspectorProps { readonly document: FormModelerDocument; readonly selectedId: string | undefined; readonly label: string; readonly actionCatalog: FormModelerActionCatalog | undefined; readonly componentCatalog: FormModelerComponentCatalog | undefined; readonly onApply: (operations: readonly FormModelerOperation[]) => void; }
export function FormModelerInspector({ document, selectedId, label, actionCatalog, componentCatalog, onApply }: InspectorProps): ReactNode {
  const entity = findEntity(document, selectedId ?? document.id);
  if (entity.kind === "field") return <FieldInspector componentCatalog={componentCatalog} field={entity.value} label={label} onApply={onApply} />;
  if (entity.kind === "action") {
    const contract = actionCatalog?.resolve(entity.value.handlerId);
    return <aside aria-label={label} className="pk-form-modeler__inspector"><h2>{entity.value.label.defaultText}</h2><dl><dt>Handler</dt><dd>{entity.value.handlerId}</dd><dt>Execution</dt><dd>{contract?.execution ?? "Unregistered"}</dd><dt>Package</dt><dd>{contract?.providerPackage ?? "Application-owned"}</dd></dl></aside>;
  }
  if (entity.kind === "element") return <aside aria-label={label} className="pk-form-modeler__inspector"><h2>{entity.value.id}</h2><dl><dt>Kind</dt><dd>{entity.value.kind}</dd><dt>Children</dt><dd>{entity.value.elements.length}</dd></dl></aside>;
  return <aside aria-label={label} className="pk-form-modeler__inspector"><h2>{document.name}</h2><dl><dt>ID</dt><dd>{document.id}</dd><dt>Revision</dt><dd>{document.revision}</dd><dt>Source locale</dt><dd>{document.sourceLocale}</dd></dl></aside>;
}

function FieldInspector({ field, label, componentCatalog, onApply }: { readonly field: FormModelerField; readonly label: string; readonly componentCatalog: FormModelerComponentCatalog | undefined; readonly onApply: (operations: readonly FormModelerOperation[]) => void }): ReactNode {
  const [text, setText] = useState(field.label.defaultText);
  useEffect(() => setText(field.label.defaultText), [field]);
  const update = (changes: Partial<FormModelerField>) => onApply([{ type: "upsertField", field: { ...field, ...changes } }]);
  const availableComponents = componentCatalog?.listFor(field.valueKind) ?? [];
  const selectedContract = field.component === undefined || field.component === null ? undefined : componentCatalog?.resolve(field.component.componentId);
  const updateOption = (key: string, value: string) => {
    if (field.component === undefined || field.component === null) return;
    update({ component: { ...field.component, options: { ...field.component.options, [key]: value } } });
  };
  return <aside aria-label={label} className="pk-form-modeler__inspector"><h2>{field.id}</h2>
    <label className="pk-form-modeler__field">Label<input onChange={event => setText(event.currentTarget.value)} onBlur={() => { if (text !== field.label.defaultText) update({ label: { ...field.label, defaultText: text } }); }} value={text} /></label>
    <label><input checked={field.required} onChange={event => update({ required: event.currentTarget.checked })} type="checkbox" /> Required</label>
    {componentCatalog !== undefined && <label className="pk-form-modeler__field">Component<select onChange={event => update({ component: event.currentTarget.value.length === 0 ? null : componentCatalog.createReference(event.currentTarget.value) })} value={field.component?.componentId ?? ""}><option value="">Default renderer</option>{availableComponents.map(contract => <option key={contract.componentId} value={contract.componentId}>{contract.displayName}</option>)}</select></label>}
    {selectedContract !== undefined && <div className="pk-form-modeler__component"><p>{selectedContract.description ?? selectedContract.displayName}</p><dl><dt>Package</dt><dd>{selectedContract.providerPackage ?? "Application-owned"}</dd><dt>Compatible version</dt><dd>{selectedContract.versionRange}</dd></dl>{(selectedContract.options ?? []).map(option => <label className="pk-form-modeler__field" key={option.key}>{option.displayName}{option.kind === "choice" || option.kind === "boolean" ? <select onChange={event => updateOption(option.key, event.currentTarget.value)} required={option.required} value={field.component?.options?.[option.key] ?? option.defaultValue ?? ""}><option disabled={option.required} value="">Select</option>{(option.kind === "boolean" ? [{ value: "true", label: "Yes" }, { value: "false", label: "No" }] : option.choices ?? []).map(choice => <option key={choice.value} value={choice.value}>{choice.label}</option>)}</select> : <input inputMode={option.kind === "integer" ? "numeric" : undefined} onChange={event => updateOption(option.key, event.currentTarget.value)} required={option.required} value={field.component?.options?.[option.key] ?? option.defaultValue ?? ""} />}</label>)}</div>}
    <dl><dt>Data path</dt><dd>{field.dataPath}</dd><dt>Value kind</dt><dd>{field.valueKind}</dd></dl>
  </aside>;
}

export function FormModelerJsonEditor({ source, accessibleLabel, cspNonce, mode, onChange }: { readonly source: string; readonly accessibleLabel: string; readonly cspNonce?: string; readonly mode: FormModelerEditorMode; readonly onChange: (source: string) => void }): ReactNode {
  const parent = useRef<HTMLDivElement>(null);
  const handle = useRef<JsonEditorHandle | null>(null);
  useEffect(() => {
    if (mode === "strictCsp") return;
    if (parent.current === null) return;
    handle.current = mountJsonEditor({ parent: parent.current, document: source, accessibleLabel, onChange, diagnostics: sourceDiagnostics, ...(cspNonce === undefined ? {} : { cspNonce }) });
    return () => { handle.current?.destroy(); handle.current = null; };
  }, [accessibleLabel, cspNonce, mode, onChange]);
  useEffect(() => handle.current?.setDocument(source), [source]);
  if (mode === "strictCsp") {
    return <textarea aria-label={accessibleLabel} className="pk-form-modeler__editor pk-form-modeler__editor--strict-csp" onChange={event => onChange(event.currentTarget.value)} spellCheck={false} value={source} />;
  }
  return <div className="pk-form-modeler__editor" ref={parent} />;
}

export function FormModelerGraph({ document, labels, labelledBy, panelId, selectedId, onSelect }: { readonly document: FormModelerDocument; readonly labels: ProgramKitFormModelerLabels; readonly labelledBy?: string; readonly panelId?: string; readonly selectedId: string | undefined; readonly onSelect: (id: string) => void }): ReactNode {
  const graph = useMemo(() => projectFormModelerGraph(document), [document]);
  return <section aria-labelledby={labelledBy} className="pk-form-modeler__panel" id={panelId} role="tabpanel"><h2>{labels.nodes}</h2><div className="pk-form-modeler__graph-nodes">{graph.nodes.map(node => {
    const rawId = node.id.slice(node.id.indexOf(":") + 1);
    return <button aria-pressed={selectedId === rawId} className="pk-form-modeler__graph-node" key={node.id} onClick={() => onSelect(rawId)} type="button"><strong>{node.label}</strong><small>{node.kind}</small></button>;
  })}</div><h2>{labels.relationships}</h2><table className="pk-form-modeler__graph-edges"><thead><tr><th>From</th><th>Relationship</th><th>To</th></tr></thead><tbody>{graph.edges.map((edge, index) => <tr key={`${edge.from}-${edge.to}-${index}`}><td>{edge.from}</td><td>{edge.kind}</td><td>{edge.to}</td></tr>)}</tbody></table></section>;
}

function sourceDiagnostics(source: string): readonly JsonEditorDiagnostic[] {
  try { parseFormModelerDocument(source); return []; }
  catch (error) { return [{ from: 0, to: Math.max(0, source.length), severity: "error", message: error instanceof Error ? error.message : "Invalid modeler document." }]; }
}

type Entity = { readonly kind: "form"; readonly value: FormModelerDocument } | { readonly kind: "field"; readonly value: FormModelerField } | { readonly kind: "action"; readonly value: FormModelerAction } | { readonly kind: "element"; readonly value: FormModelerElement };
function findEntity(document: FormModelerDocument, id: string): Entity {
  if (document.id === id) return { kind: "form", value: document };
  const field = document.fields.find(item => item.id === id); if (field !== undefined) return { kind: "field", value: field };
  const action = document.actions.find(item => item.id === id); if (action !== undefined) return { kind: "action", value: action };
  const element = findElement(document.layout, id); return element === undefined ? { kind: "form", value: document } : { kind: "element", value: element };
}
function findElement(element: FormModelerElement, id: string): FormModelerElement | undefined { if (element.id === id) return element; for (const child of element.elements) { const match = findElement(child, id); if (match !== undefined) return match; } return undefined; }
function refreshSelection(snapshot: FormModelerSnapshot, setSnapshot: (snapshot: FormModelerSnapshot) => void, onChange?: (snapshot: FormModelerSnapshot) => void): void { setSnapshot(snapshot); onChange?.(snapshot); }

function createPaletteAddition(document: FormModelerDocument, selectedId: string | undefined, item: FormModelerPaletteItem): { readonly operations: readonly FormModelerOperation[]; readonly selectedId: string } {
  const selectedElement = selectedId === undefined ? undefined : findElement(document.layout, selectedId);
  const parentId = selectedElement !== undefined && containerKinds.has(selectedElement.kind) ? selectedElement.id : document.layout.id;
  const insertionIndex = (findElement(document.layout, parentId)?.elements.length) ?? 0;
  if (item.type === "field") {
    const fieldId = nextDocumentId(document, "field");
    const field: FormModelerField = {
      id: fieldId,
      dataPath: `/${fieldId}`,
      valueKind: item.valueKind,
      required: false,
      label: { key: `fields.${fieldId}`, defaultText: `Field ${fieldId.slice("field-".length)}` }
    };
    const controlId = nextDocumentId(document, `${fieldId}-control`);
    return {
      operations: [
        { type: "upsertField", field },
        { type: "insertElement", parentId, index: insertionIndex, element: { id: controlId, kind: "control", fieldId, elements: [] } }
      ],
      selectedId: fieldId
    };
  }
  const prefix = item.elementKind.replace(/[A-Z]/g, match => `-${match.toLowerCase()}`);
  const elementId = nextDocumentId(document, prefix);
  const element: FormModelerElement = {
    id: elementId,
    kind: item.elementKind,
    elements: [],
    ...(item.elementKind === "text" ? { text: { key: `content.${elementId}`, defaultText: "Explanatory text" } } : {})
  };
  return { operations: [{ type: "insertElement", parentId, index: insertionIndex, element }], selectedId: elementId };
}

const containerKinds = new Set<FormModelerElement["kind"]>(["group", "horizontalLayout", "verticalLayout", "wizard", "step"]);

function nextDocumentId(document: FormModelerDocument, prefix: string): string {
  const ids = new Set<string>([document.id, ...document.fields.map(field => field.id), ...document.actions.map(action => action.id)]);
  const visit = (element: FormModelerElement) => { ids.add(element.id); element.elements.forEach(visit); };
  visit(document.layout);
  let number = 1;
  while (ids.has(`${prefix}-${number}`)) number += 1;
  return `${prefix}-${number}`;
}

function countElements(element: FormModelerElement): number {
  return 1 + element.elements.reduce((count, child) => count + countElements(child), 0);
}

// src/typescript/packages/forms-schema-modeler-angular/src/index.ts
import { ChangeDetectionStrategy, Component, ElementRef, EventEmitter, Input, Output, ViewChild, type AfterViewChecked, type OnDestroy, type OnInit } from "@angular/core";
import { codeMirrorJsonEditorAdapter } from "@orbyss/program-kit-forms-codemirror";
import type { JsonEditorAdapter, JsonEditorHandle } from "@orbyss/program-kit-forms-editor-contracts";
import {
  SchemaModelerSession,
  listSchemaModelerChildren,
  parseCompiledJsonSchema,
  projectSchemaModelerGraph,
  serializeCompiledJsonSchema,
  type SchemaModelerDocument,
  type SchemaModelerNode,
  type SchemaModelerOperation,
  type SchemaModelerSnapshot,
  type SchemaModelerValueKind
} from "@orbyss/program-kit-forms-schema-modeler";
import { programKitClassName, type ProgramKitClassNames } from "@orbyss/program-kit-ui-theme";

export type SchemaModelerAngularView = "design" | "json" | "graph";
export type SchemaModelerAngularEditorMode = "rich" | "strictCsp";
export type SchemaModelerAngularThemeSlot = "root" | "toolbar" | "diagnostics" | "tabs" | "workspace" | "palette" | "tree" | "canvas" | "canvasBlock" | "inspector" | "editor" | "graph" | "graphNode";
export interface ProgramKitSchemaModelerAngularLabels { readonly undo: string; readonly redo: string; readonly commit: string; readonly applyJson: string; readonly design: string; readonly json: string; readonly graph: string; readonly palette: string; readonly structure: string; readonly canvas: string; readonly inspector: string; readonly editor: string; readonly remove: string; }
const defaults: ProgramKitSchemaModelerAngularLabels = Object.freeze({ undo: "Undo", redo: "Redo", commit: "Commit schema", applyJson: "Apply JSON Schema", design: "Design", json: "JSON Schema", graph: "Graph", palette: "Schema types", structure: "Schema structure", canvas: "Schema canvas", inspector: "Properties", editor: "JSON Schema source", remove: "Remove node" });
const kinds: readonly SchemaModelerValueKind[] = ["string", "integer", "number", "boolean", "object", "array"];

@Component({
  selector: "program-kit-schema-modeler",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [class]="slotClass('root', 'pk-schema-modeler', className)" data-pk-slot="schema-modeler.root" [attr.data-pk-unstyled]="unstyled || null">
      <div [class]="slotClass('toolbar', 'pk-schema-modeler__toolbar')" data-pk-slot="schema-modeler.toolbar" role="toolbar" aria-label="Schema modeler actions">
        <button type="button" [disabled]="!snapshot.canUndo" (click)="refresh(session.undo())">{{ text.undo }}</button>
        <button type="button" [disabled]="!snapshot.canRedo" (click)="refresh(session.redo())">{{ text.redo }}</button>
        <button type="button" (click)="commit.emit({ document: snapshot.document, sequence: snapshot.sequence })">{{ text.commit }}</button>
      </div>
      @if (error) { <p [class]="slotClass('diagnostics', 'pk-schema-modeler__diagnostics')" data-pk-slot="schema-modeler.diagnostics" role="alert">{{ error }}</p> }
      <div [class]="slotClass('tabs', 'pk-schema-modeler__tabs')" data-pk-slot="schema-modeler.tabs" role="tablist" aria-label="Schema modeler views">
        @for (candidate of views; track candidate) { <button type="button" role="tab" [attr.aria-selected]="view === candidate" (click)="setView(candidate)">{{ viewLabel(candidate) }}</button> }
      </div>
      @if (view === 'design') {
        <section [class]="slotClass('workspace', 'pk-schema-modeler__workspace')" data-pk-slot="schema-modeler.workspace">
          <aside [class]="slotClass('palette', 'pk-schema-modeler__palette')" data-pk-slot="schema-modeler.palette" [attr.aria-label]="text.palette"><h2>{{ text.palette }}</h2>
            @for (kind of kinds; track kind) { <button type="button" [disabled]="!canAdd(kind)" (click)="add(kind)">Add {{ kind }}</button> }
          </aside>
          <nav [class]="slotClass('tree', 'pk-schema-modeler__tree')" data-pk-slot="schema-modeler.tree" [attr.aria-label]="text.structure"><h2>{{ text.structure }}</h2><ul>
            @for (node of orderedNodes(); track node.id) { <li><button type="button" [attr.aria-current]="snapshot.selectedId === node.id" (click)="select(node.id)">{{ node.propertyName || snapshot.document.title }} <small>{{ node.valueKind }}</small></button></li> }
          </ul></nav>
          <section [class]="slotClass('canvas', 'pk-schema-modeler__canvas')" data-pk-slot="schema-modeler.canvas" [attr.aria-label]="text.canvas"><h2>{{ text.canvas }}</h2>
            @for (node of orderedNodes(); track node.id) { <div [class]="slotClass('canvasBlock', 'pk-schema-modeler__block')" data-pk-slot="schema-modeler.canvasBlock"><button type="button" [attr.aria-pressed]="snapshot.selectedId === node.id" (click)="select(node.id)"><strong>{{ node.propertyName || snapshot.document.title }}</strong><small>{{ node.valueKind }}{{ node.required ? ' · required' : '' }}</small></button></div> }
          </section>
          <aside [class]="slotClass('inspector', 'pk-schema-modeler__inspector')" data-pk-slot="schema-modeler.inspector" [attr.aria-label]="text.inspector"><h2>{{ text.inspector }}</h2>
            @if (selected(); as node) { <dl><dt>ID</dt><dd>{{ node.id }}</dd><dt>Type</dt><dd>{{ node.valueKind }}</dd></dl>
              @if (node.propertyName !== null) { <label>Property name<input [value]="node.propertyName" (change)="updateProperty(node, value($event))"></label> }
              <label>Title<input [value]="node.title || ''" (change)="updateTitle(node, value($event))"></label>
              @if (node.propertyName !== null) { <label><input type="checkbox" [checked]="node.required" (change)="updateRequired(node, checked($event))"> Required</label> }
              @if (node.id !== snapshot.document.rootNodeId) { <button type="button" (click)="remove(node.id)">{{ text.remove }}</button> }
            }
          </aside>
        </section>
      }
      @if (view === 'json') { <section role="tabpanel"><div #editorHost [hidden]="editorMode === 'strictCsp'" [class]="slotClass('editor', 'pk-schema-modeler__editor')" data-pk-slot="schema-modeler.editor"></div>
        @if (editorMode === 'strictCsp') { <textarea [class]="slotClass('editor', 'pk-schema-modeler__editor pk-schema-modeler__editor--strict')" data-pk-slot="schema-modeler.editor" [attr.aria-label]="text.editor" spellcheck="false" [value]="source" (input)="source = value($event)"></textarea> }
        <button type="button" (click)="applySource()">{{ text.applyJson }}</button></section> }
      @if (view === 'graph') { <section [class]="slotClass('graph', 'pk-schema-modeler__graph')" data-pk-slot="schema-modeler.graph" role="tabpanel"><div class="pk-schema-modeler__graph-nodes">
        @for (node of graph().nodes; track node.id) { <button type="button" [class]="slotClass('graphNode', 'pk-schema-modeler__graph-node')" data-pk-slot="schema-modeler.graphNode" [attr.aria-pressed]="snapshot.selectedId === node.id" (click)="select(node.id)"><strong>{{ node.label }}</strong><small>{{ node.valueKind }}</small></button> }
        </div><table><thead><tr><th>From</th><th>Relationship</th><th>To</th></tr></thead><tbody>@for (edge of graph().edges; track edge.from + edge.to) { <tr><td>{{ edge.from }}</td><td>{{ edge.label || edge.kind }}</td><td>{{ edge.to }}</td></tr> }</tbody></table></section> }
    </section>
  `
})
export class ProgramKitSchemaModelerAngularComponent implements OnInit, AfterViewChecked, OnDestroy {
  @Input({ required: true }) session!: SchemaModelerSession;
  @Input() initialView: SchemaModelerAngularView = "design";
  @Input() labels: Partial<ProgramKitSchemaModelerAngularLabels> = {};
  @Input() editorMode: SchemaModelerAngularEditorMode = "rich";
  @Input() editorAdapter: JsonEditorAdapter = codeMirrorJsonEditorAdapter;
  @Input() cspNonce?: string;
  @Input() classNames: ProgramKitClassNames<SchemaModelerAngularThemeSlot> = {};
  @Input() className?: string;
  @Input() unstyled = false;
  @Output() readonly change = new EventEmitter<SchemaModelerSnapshot>();
  @Output() readonly commit = new EventEmitter<{ readonly document: SchemaModelerDocument; readonly sequence: number }>();
  @ViewChild("editorHost") editorHost?: ElementRef<HTMLElement>;
  readonly views: readonly SchemaModelerAngularView[] = ["design", "json", "graph"];
  readonly kinds = kinds;
  snapshot!: SchemaModelerSnapshot;
  view: SchemaModelerAngularView = "design";
  source = "";
  error = "";
  private editor: JsonEditorHandle | undefined;
  private editorElement: HTMLElement | undefined;
  private command = 1;
  get text(): ProgramKitSchemaModelerAngularLabels { return { ...defaults, ...this.labels }; }
  ngOnInit(): void { this.view = this.initialView; this.snapshot = this.session.snapshot(); this.source = serializeCompiledJsonSchema(this.snapshot.document); }
  ngAfterViewChecked(): void { const host = this.view === "json" && this.editorMode === "rich" ? this.editorHost?.nativeElement : undefined; if (host === this.editorElement) return; this.destroyEditor(); if (host !== undefined) { this.editorElement = host; this.editor = this.editorAdapter.mount({ parent: host, document: this.source, accessibleLabel: this.text.editor, onChange: value => { this.source = value; }, diagnostics: source => { try { parseCompiledJsonSchema(source); return []; } catch (reason) { return [{ from: 0, to: source.length, severity: "error", message: publicError(reason) }]; } }, ...(this.cspNonce === undefined ? {} : { cspNonce: this.cspNonce }) }); } }
  ngOnDestroy(): void { this.destroyEditor(); }
  slotClass(name: SchemaModelerAngularThemeSlot, base: string, extra?: string): string | undefined { return programKitClassName(base, [this.classNames[name], extra].filter(Boolean).join(" ") || undefined, this.unstyled); }
  viewLabel(view: SchemaModelerAngularView): string { return this.text[view]; }
  setView(view: SchemaModelerAngularView): void { this.view = view; if (view !== "json") this.destroyEditor(); }
  refresh(next: SchemaModelerSnapshot): void { this.snapshot = next; this.source = serializeCompiledJsonSchema(next.document); this.editor?.setDocument(this.source); this.error = ""; this.change.emit(next); }
  apply(operations: readonly SchemaModelerOperation[]): boolean { try { this.refresh(this.session.apply({ commandId: `schema-angular:${this.snapshot.sequence}:${this.command++}`, expectedSequence: this.snapshot.sequence, operations })); return true; } catch (reason) { this.error = publicError(reason); return false; } }
  applySource(): void { try { this.apply([{ type: "replaceDocument", document: parseCompiledJsonSchema(this.source, this.snapshot.document.id, this.snapshot.document.revision) }]); } catch (reason) { this.error = publicError(reason); } }
  select(id: string): void { this.refresh(this.session.select(id)); }
  selected(): SchemaModelerNode | undefined { return this.snapshot.document.nodes.find(node => node.id === this.snapshot.selectedId) ?? this.snapshot.document.nodes.find(node => node.id === this.snapshot.document.rootNodeId); }
  orderedNodes(): readonly SchemaModelerNode[] { const result: SchemaModelerNode[] = []; const visit = (id: string) => { const node = this.snapshot.document.nodes.find(value => value.id === id); if (node === undefined) return; result.push(node); listSchemaModelerChildren(this.snapshot.document, id).forEach(child => visit(child.id)); }; visit(this.snapshot.document.rootNodeId); return result; }
  graph(): ReturnType<typeof projectSchemaModelerGraph> { return projectSchemaModelerGraph(this.snapshot.document); }
  canAdd(_kind: SchemaModelerValueKind): boolean { const selected = this.selected(); const parent = selected !== undefined && (selected.valueKind === "object" || selected.valueKind === "array") ? selected : this.snapshot.document.nodes.find(node => node.id === selected?.parentId); return parent !== undefined && !(parent.valueKind === "array" && listSchemaModelerChildren(this.snapshot.document, parent.id).length > 0); }
  add(kind: SchemaModelerValueKind): void { const selected = this.selected(); const parent = selected !== undefined && (selected.valueKind === "object" || selected.valueKind === "array") ? selected : this.snapshot.document.nodes.find(node => node.id === selected?.parentId); if (parent === undefined || !this.canAdd(kind)) return; const children = listSchemaModelerChildren(this.snapshot.document, parent.id); const id = nextId(this.snapshot.document, kind); const node: SchemaModelerNode = { id, parentId: parent.id, propertyName: parent.valueKind === "object" ? nextProperty(children, kind) : null, order: children.length, valueKind: kind, required: false, ...(kind === "object" ? { additionalProperties: false } : {}) }; const operations: SchemaModelerOperation[] = [{ type: "insertNode", parentId: parent.id, index: children.length, node }]; if (kind === "array") operations.push({ type: "insertNode", parentId: id, index: 0, node: { id: `${id}-item`, parentId: id, propertyName: null, order: 0, valueKind: "string", required: false } }); if (this.apply(operations)) this.select(id); }
  remove(id: string): void { this.apply([{ type: "removeNode", nodeId: id }]); }
  updateProperty(node: SchemaModelerNode, propertyName: string): void { this.apply([{ type: "updateNode", node: { ...node, propertyName } }]); }
  updateTitle(node: SchemaModelerNode, title: string): void { this.apply([{ type: "updateNode", node: { ...node, title: title.length === 0 ? null : title } }]); }
  updateRequired(node: SchemaModelerNode, required: boolean): void { this.apply([{ type: "updateNode", node: { ...node, required } }]); }
  value(event: Event): string { return (event.currentTarget as HTMLInputElement | HTMLTextAreaElement).value; }
  checked(event: Event): boolean { return (event.currentTarget as HTMLInputElement).checked; }
  private destroyEditor(): void { this.editor?.destroy(); this.editor = undefined; this.editorElement = undefined; }
}

function publicError(reason: unknown): string { return reason instanceof Error ? reason.message : "The schema operation could not be completed."; }
function nextId(document: SchemaModelerDocument, kind: string): string { let value = 1; while (document.nodes.some(node => node.id === `${kind}-${value}` || node.id === `${kind}-${value}-item`)) value += 1; return `${kind}-${value}`; }
function nextProperty(children: readonly SchemaModelerNode[], kind: string): string { let value = 1; while (children.some(node => node.propertyName === `${kind}${value}`)) value += 1; return `${kind}${value}`; }
